spring.application.name=banking-app
server.port=${PORT:8080}

# ===============================
# LOCAL MYSQL (only used locally)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/banking_app?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:suyog123}

# Driver auto-detect (MySQL locally, Postgres on Render)
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${SPRING_JPA_PLATFORM:org.hibernate.dialect.MySQLDialect}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false